// user
export const FETCHED_USER = "FETCHED_USER";
export const REQUESTED_USER = "REQUESTED_USER";
export const REQUESTED_USER_SUCCEEDED = "REQUESTED_USER_SUCCEEDED";
export const REQUESTED_USER_FAILED = "REQUESTED_USER_FAILED";
export const LOG_OUT_USER = "LOG_OUT_USER";

// feeds
export const FETCHED_FEEDS = "FETCHED_FEEDS";
export const REQUESTED_FEEDS = "REQUESTED_FEEDS";
export const REQUESTED_FEEDS_SUCCEEDED = "REQUESTED_FEEDS_SUCCEEDED";
export const REQUESTED_FEEDS_FAILED = "REQUESTED_FEEDS_FAILED";
export const REMOVE_FEED = "REMOVE_FEED";
export const ADD_FEED = "ADD_FEED";
export const SET_CURRENT_FEED = "SET_CURRENT_FEED";
export const SET_ARTICLE_ID = "SET_ARTICLE_ID";